# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -Werror -g

# Source file
SRC = db.c

# Object file
OBJ = $(SRC:.c=.o)

# Executable name
TARGET = db_app

# Build the executable
all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

# Compile .c files to .o files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Run the executable
run: $(TARGET)
	./$(TARGET)

# Clean the build files
clean:
	rm -f $(OBJ) $(TARGET)

# Phony targets
.PHONY: all clean run
